on:
  pull_request_target:
    branches:
      - auto-backport-2
    types:
      - labeled
      - closed

jobs:
  backport:
    name: Backport PR
    # github.event.pull_request.merged == true
    if: |
      contains(github.event.pull_request.labels.*.name, 'auto-backport')
      && (
        (github.event.action == 'labeled' && github.event.label.name == 'auto-backport')
        || (github.event.action == 'closed')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'elastic/kibana-github-actions'
          ref: main
          path: ./actions

      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: Run Backport
        uses: ./actions/backport
        with:
          branch: auto-backport-2
          github_token: ${{secrets.KIBANAMACHINE_TOKEN}}
          commit_user: kibanamachine
          commit_email: 42973632+kibanamachine@users.noreply.github.com
